[package]
name = "gp"
version = "0.1.0"
authors = ["zhoutianyang <zhoutianyang@100etech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap="2.33.0"
